workflows:
  ios-release:
    name: "SLM iOS"
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: 🧹 Clean & Fetch Packages
        script: |
          flutter clean
          flutter pub get

      - name: 📌 Generate Podfile if not existing
        script: |
          if [ ! -f ios/Podfile ]; then
            flutter build ios --no-codesign
          fi

      - name: ✅ Set minimum iOS version 14.0
        script: |
          echo "🔧 Updating Podfile to iOS 14.0"
          sed -i '' 's/platform :ios.*/platform :ios, '\''14.0'\''/' ios/Podfile || echo "platform :ios, '14.0'" >> ios/Podfile

      - name: 📦 Install pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install
          cd ..

      - name: 🚀 Build IPA
        script: |
          flutter build ipa --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
